name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py38", "py39", "py310", "py311"]'
